- name: Template file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: docker-compose.yml

- name: Deploy web app
  become: true
  block:
    - name: Wipe docker containers
      community.docker.docker_container:
        state: absent
      when: web_app_full_wipe
      tags: wipe

    - name: Run docker container
      community.docker.docker_container:
        state: started
        pull: true
  module_defaults:
    community.docker.docker_container:
      image: klemencja/app_python
      name: web_app_python
  tags: deploy
