- name: Install pip
  apt: name=python3-pip state=present

- name: Include install_docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Include install_compose
  ansible.builtin.include_tasks:
    file: install_compose.yml
