scrape_configs:
  - job_name: 'loki_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3100']
  - job_name: 'prometheus_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
